#!/bin/bash

PWD=$(pwd)

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
             https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -sf $PWD/.vimrc ~/.vimrc

vim +PlugInstall +qall

